set_property LOC R2 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports {clk}]

set_property LOC E18 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports {led}]
set_property LOC L13 [get_ports clkout[0]]
set_property IOSTANDARD LVCMOS33 [get_ports {clkout[0]}]
set_property LOC N13 [get_ports clkout[1]]
set_property IOSTANDARD LVCMOS33 [get_ports {clkout[1]}]
set_property LOC L16 [get_ports clkout[2]]
set_property IOSTANDARD LVCMOS33 [get_ports {clkout[2]}]
