set_property LOC U22 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports {clk}]

set_property LOC P4 [get_ports key]
set_property IOSTANDARD LVCMOS33 [get_ports {key}]

set_property LOC T23 [get_ports led[0]]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property LOC R23 [get_ports led[1]]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property LOC AB24 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property LOC AA25 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property LOC AC24 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]

set_property LOC G4 [get_ports {debug[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug[0]}]
set_property LOC F4 [get_ports {debug[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug[1]}]
set_property LOC G2 [get_ports {debug[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug[2]}]
set_property LOC G1 [get_ports {debug[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug[3]}]
set_property LOC J4 [get_ports {debug[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug[4]}]
set_property LOC H4 [get_ports {debug[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug[5]}]
set_property LOC H2 [get_ports {debug[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug[6]}]
set_property LOC H1 [get_ports {debug[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug[7]}]

set_property LOC T2 [get_ports {debug[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug[8]}]
set_property LOC R2 [get_ports {debug[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug[9]}]
set_property LOC U2 [get_ports {debug[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug[10]}]
set_property LOC U1 [get_ports {debug[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug[11]}]

set_property LOC H21 [get_ports clkout]
set_property IOSTANDARD LVCMOS33 [get_ports {clkout}]
