set_property LOC U22 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports {clk}]

set_property LOC T23 [get_ports led[0]]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property LOC R23 [get_ports led[1]]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property LOC AB24 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property LOC AA25 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property LOC AC24 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]

set_property LOC G21 [get_ports {debug[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug[0]}]
set_property LOC H22 [get_ports {debug[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug[1]}]
set_property LOC J21 [get_ports {debug[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug[2]}]
set_property LOC K26 [get_ports {debug[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug[3]}]
set_property LOC G20 [get_ports {debug[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug[4]}]

set_property LOC H21 [get_ports clkout]
set_property IOSTANDARD LVCMOS33 [get_ports {clkout}]
